config/routes.rb
Rails.application.routes.draw do
  resources :push_notifications
  resources :platform_endpoints, only: [:create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "platform_endpoints#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/platform_endpoint.rb
class PlatformEndpoint
  include ActiveModel::Model
  attr_accessor :token, :endpoint_arn

  def save
    client = Aws::SNS::Client.new(region: Settings.region)
    result = client.create_platform_endpoint({
      platform_application_arn: Settings.platform_application_arn,
      token: token,
    })
  end

  class << self
    def all
      client = Aws::SNS::Client.new(region: Settings.region)
      res = client.list_endpoints_by_platform_application(
        {
          platform_application_arn: Settings.platform_application_arn
        }
      )
      res.endpoints
    end
  end
end

app/models/push_notification.rb
class PushNotification
  include ActiveModel::Model
  attr_accessor :message, :endpoint_arn

  def save
    client = Aws::SNS::Client.new(region: Settings.region)
    client.publish(
      {
        target_arn: endpoint_arn,
        message: message
      }
    )
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/platform_endpoints_controller.rb
class PlatformEndpointsController < ApplicationController
  before_action :set_platform_endpoint, only: [:show]
  protect_from_forgery with: :null_session, only: [:create]

  # GET /platform_endpoints
  # GET /platform_endpoints.json
  def index
    @platform_endpoints = PlatformEndpoint.all
  end

  # GET /platform_endpoints/1
  # GET /platform_endpoints/1.json
  def show
  end

  # POST /platform_endpoints
  # POST /platform_endpoints.json
  def create
    @platform_endpoint = PlatformEndpoint.new(platform_endpoint_params)

    respond_to do |format|
      if @platform_endpoint.save
        format.html { redirect_to @platform_endpoint, notice: 'Platform endpoint was successfully created.' }
        format.json { render :show, status: :created, location: @platform_endpoint }
      else
        format.html { render :new }
        format.json { render json: @platform_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform_endpoint
      @platform_endpoint = PlatformEndpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_endpoint_params
      params.require(:platform_endpoint).permit(:token)
    end
end

app/controllers/push_notifications_controller.rb
class PushNotificationsController < ApplicationController
  before_action :set_push_notification, only: [:show, :edit, :update, :destroy]

  # GET /push_notifications
  # GET /push_notifications.json
  def index
    @push_notifications = PushNotification.all
  end

  # GET /push_notifications/1
  # GET /push_notifications/1.json
  def show
  end

  # GET /push_notifications/new
  def new
    @push_notification = PushNotification.new(endpoint_arn: params[:endpoint_arn])
  end

  # GET /push_notifications/1/edit
  def edit
  end

  # POST /push_notifications
  # POST /push_notifications.json
  def create
    @push_notification = PushNotification.new(push_notification_params)

    respond_to do |format|
      if @push_notification.save
        format.html { redirect_to @push_notification, notice: 'Push notification was successfully created.' }
        format.json { render :show, status: :created, location: @push_notification }
      else
        format.html { render :new }
        format.json { render json: @push_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /push_notifications/1
  # PATCH/PUT /push_notifications/1.json
  def update
    respond_to do |format|
      if @push_notification.update(push_notification_params)
        format.html { redirect_to @push_notification, notice: 'Push notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @push_notification }
      else
        format.html { render :edit }
        format.json { render json: @push_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /push_notifications/1
  # DELETE /push_notifications/1.json
  def destroy
    @push_notification.destroy
    respond_to do |format|
      format.html { redirect_to push_notifications_url, notice: 'Push notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_push_notification
      @push_notification = PushNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def push_notification_params
      params.require(:push_notification).permit(:message, :endpoint_arn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/platform_endpoints_helper.rb
module PlatformEndpointsHelper
end

app/helpers/push_notifications_helper.rb
module PushNotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushNotificationSampleRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/platform_endpoints/_form.html.slim
= form_for @platform_endpoint do |f|
  - if @platform_endpoint.errors.any?
    #error_explanation
      h2 = "#{pluralize(@platform_endpoint.errors.count, "error")} prohibited this platform_endpoint from being saved:"
      ul
        - @platform_endpoint.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/platform_endpoints/index.html.slim
h1 Listing platform_endpoints

table
  thead
    tr
      th
        | Endpoint arn
      th
        | Token
      th
        | Enabled
      th
        | Send message

  tbody
    - @platform_endpoints.each do |endpoint|
      tr
        td
          = endpoint.endpoint_arn
        td
          = endpoint.attributes["Token"]
        td
          = endpoint.attributes["Enabled"]
        td
          = link_to "Send message", new_push_notification_path(endpoint_arn: endpoint.endpoint_arn)
br

app/views/platform_endpoints/show.html.slim
p#notice = notice


= link_to 'Edit', edit_platform_endpoint_path(@platform_endpoint)
'  |
= link_to 'Back', platform_endpoints_path

app/views/push_notifications/_form.html.slim
= form_for @push_notification do |f|
  - if @push_notification.errors.any?
    #error_explanation
      h2 = "#{pluralize(@push_notification.errors.count, "error")} prohibited this push_notification from being saved:"
      ul
        - @push_notification.errors.full_messages.each do |message|
          li = message

  = f.text_area :message
  = f.hidden_field :endpoint_arn
  .actions = f.submit

app/views/push_notifications/edit.html.slim
h1 Editing push_notification

== render 'form'

= link_to 'Show', @push_notification
'  |
= link_to 'Back', push_notifications_path

app/views/push_notifications/index.html.slim
h1 Listing push_notifications

table
  thead
    tr
      th
      th
      th

  tbody
    - @push_notifications.each do |push_notification|
      tr
        td = link_to 'Show', push_notification
        td = link_to 'Edit', edit_push_notification_path(push_notification)
        td = link_to 'Destroy', push_notification, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Push notification', new_push_notification_path

app/views/push_notifications/new.html.slim
h1 New push_notification

== render 'form'

= link_to 'Back', push_notifications_path

app/views/push_notifications/show.html.slim
p#notice = notice


= link_to 'Edit', edit_push_notification_path(@push_notification)
'  |
= link_to 'Back', push_notifications_path